# Generated by Django 3.2.2 on 2022-02-10 10:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('serviceName', models.CharField(blank=True, max_length=255)),
                ('serviceCode', models.CharField(blank=True, max_length=255)),
                ('serviceDate', models.DateField(default=datetime.date.today)),
                ('trash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
