# Generated by Django 3.2.2 on 2022-02-11 05:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothDetails',
            fields=[
                ('clothId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('clothName', models.CharField(blank=True, max_length=255)),
                ('clothNameArabic', models.TextField(blank=True)),
                ('clothCode', models.CharField(blank=True, max_length=255)),
                ('clothDate', models.DateField(default=datetime.date.today)),
                ('clothImg', models.ImageField(blank=True, default='pic.jpg', upload_to='images')),
                ('posView', models.BooleanField(default=False)),
                ('clothCount', models.IntegerField(default=0)),
                ('trash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
