# Generated by Django 3.2.2 on 2022-02-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pricedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedetails',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricedetails',
            name='clothType',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pricedetails',
            name='serviceName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
