# Generated by Django 3.2.2 on 2022-02-11 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220211_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('acTypeId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('acTypeName', models.CharField(blank=True, max_length=255)),
                ('trash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
