# Generated by Django 3.2.2 on 2022-02-11 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('plantId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('plantName', models.TextField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('clothType', models.CharField(blank=True, max_length=255)),
                ('contactName', models.CharField(blank=True, max_length=255)),
                ('contactNumber', models.BigIntegerField(blank=True)),
                ('trash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
